# For developers only:
#  Remove the cmorfixer environment:
#   conda deactivate
#   rm -rf ${mambapath}/envs/cmorfixer
#  Create the cmorfixer environment:
#    activatemamba                               # alias activatemamba='source ${mambapath}/etc/profile.d/conda.sh'
#    mamba update -y --name base mamba           # For updating mamba itself
#    mamba env create -f environment.yml         # Create the cmorfixer environment
#  Basic tests:
#   which python                                 # ${mambapath}/envs/cmorfixer/bin/python
#   python --version                             # Python 3.12.5
#   ./cmor-fixer.py -h

name: cmorfixer
channels:
- conda-forge
- nodefaults
dependencies:
- netcdf4
- numpy
